name: shopping_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  bloc: ^8.1.4
  buttons_tabbar: ^1.3.8
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_otp_text_field: ^1.1.3+2
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  order_tracker: ^0.0.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  timeline_tile: ^2.0.0
  timelines: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/demo.webp
    - assets/cod.png
    - assets/gpay.png
    - assets/paytm.png
    - assets/upi.png
